"""
LangGraph State Definition for the Planning Agent.
Defines the AgentState TypedDict that holds messages and todos.
"""

from typing import TypedDict, List, Dict, Annotated
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    State schema for the ReAct planning agent.
    
    Attributes:
        messages: List of conversation messages (managed by LangGraph)
        todos: List of todo items generated by write_todos tool
    """
    messages: Annotated[list, add_messages]
    todos: List[Dict]
